version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt  # Ensures dependencies are installed from the requirements.txt
    
sphinx:
  configuration: docs/source/conf.py
  
envs:
  - QT_QPA_PLATFORM=offscreen  # Disable Qt GUI (forces offscreen mode)
  - MPLCONFIGDIR=/tmp/matplotlib  # Ensures Matplotlib configuration doesn't attempt to write to user directories
