version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - export QT_QPA_PLATFORM=offscreen  # Set Qt to offscreen mode

python:
  install:
    - requirements: docs/requirements.txt  # Ensures dependencies are installed from the requirements.txt

sphinx:
  configuration: docs/source/conf.py
