version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - libosmesa6
    - libosmesa6-dev

python:
  install:
    - requirements: docs/requirements.txt  # Ensures dependencies are installed from the requirements.txt

sphinx:
  configuration: docs/source/conf.py
